### ISSUE TITLE
Create the web app

### ISSUE THREAD

**Issue by DerekStride** [GraphQL-Query-Planner/project#1]
We need to create a Rails app we'll be using to test our Query Planner, we should get it up and running on the latest version of Rails (v5.1) and the latest version of Ruby (v2.4.1).

We'll also want to alway make sure we're using an up to date version of [`graphql-ruby`](https://github.com/rmosolgo/graphql-ruby).

Since we'll be working with the underlying data layer a lot we'll want to make sure we all have the same version of MySQL installed. The [download page](https://dev.mysql.com/downloads) lists v5.7.19 as the latest and that seems to be the same version homebrew installs.

**Comment by ismail-syed** [comment]
https://github.com/GraphQL-Query-Planner/webscale/pull/3
