### ISSUE TITLE
Expand planner milestones

### ISSUE THREAD

**Issue by DerekStride** [GraphQL-Query-Planner/project#10]

**Comment by DerekStride** [comment]
@ismail-syed @justinkrol 

I've added these as the main planner milestones

- October 31st - Planner MVP - identifying queries and MySQL plans

I'm hoping to have this finished before reading week (Oct 23rd - 27th) but I listed it as after just so that if we want to take the week off and still be on schedule we'll have a goal to work towards.

- December20th - Refactor Planner to support multiple backends / query response time

I figured december will likely be mostly exams so this may be finished up beforehand as well so we can take a break while studying.

- February 1st - ElasticSearch, MongoDB, Cassandra Integrations

I suspect we can each pick one datastore that's not relational (not necessarily these 3) and build adapters for them. That way we can all dive deep into one specific one and get exposure to the others via the code reviews.

- March 1st - Upstream PRs Merged (if any) / Standalone Gem Published

I'm hoping by the last milestone that most of the planner work is done and we'll just have to focus on building a nice demo app. Maybe publish the Gem or submit a PR upstream if the work seems valuable enough.

**Comment by ismail-syed** [comment]
@DerekStride I was hoping that we could 🚢 the Ruby Gem incrementally throughout the project. This will allow us to incrementally build out Webscale too. We can even 🚢  whatever fork we have under a `v0.0.1` release. We can save the `v1.0.0` version for the March 1st deadline.

 We could rename the package to `graphql-planner` and ship incrementally using that. Thoughts?

**Comment by DerekStride** [comment]
@ismail-syed sounds good to me :+1:
