### ISSUE TITLE
Describe how our GitHub organization is structured. 

### ISSUE THREAD

**Issue by ismail-syed** [GraphQL-Query-Planner/project#11]
See title

**Comment by justinkrol** [comment]
I've added a section to the [proposal](https://docs.google.com/document/d/1fun70FFe5heoWo8c3EdgCStcaAxJa-5wjn2Mg0Ahwhc/edit) called `Project Management`. It talks about how we will use Github for:
- Version control
- Issue tracking
- Code Review
- Milestones
- Health checks

cc @ismail-syed @DerekStride
