### ISSUE TITLE
Final Report Feedback Points

### ISSUE THREAD

**Issue by justinkrol** [GraphQL-Query-Planner/project#23]
- [x] **(Justin)** make sure to talk about webscale in the abstract
------------
- [x] **(Justin)** 6.3 might want to say what you mean by "N+1" in a little more detail here.
------------
- [x] **(Justin)** 6.4 again, you may want to talk about webscale here, as a way of validating your solution.
------------
- [x] **(Justin)** 7.4 seems a bit too tool-oriented. Tools are there to support a process. Maybe emphasize the process, and show hoe the tools support it.
------------
- [x] **(Justin)** 7.4.6 "we will meet"... should be "we met"? Same issue in 7.4.7 and possibly other places. In general, I recommend that you print the report and read it in its entirety in one go, and you'll spot issues like these.
------------
- [x] **(Ismail)** 7.7, 7.8 up to 7.11 might need to be under the same umbrella, maybe something called "Background". **(Justin)** In the intro of that Background, you can explain why it is necessary to talk about REST first,  and how it relates to GraphQL, and the rest.
------------
- [x] **(Justin)** 7.8.1 "you can picture", "you can create": a bit too colloquial for a report. This is true in 8.2.3 and other places as well. Also between end of 8.2.3 and 8.3
------------
- [x] Chap 8 might need an intro. In general, start each chapter with a little intro so we know what we are going to read and why. End each chapter with some conclusion and a transition to the next chapter. So we understand how what we just read is relevant to what we're going to read. That's actually true between sections and subsections as well. We shouldn't "jump" from one subsection to the next without proper transition. example, between 8.1.2 and 8.1.3, or between 8.1.3 and 8.2, or between 8.4.4 and 9
------------
- [x] "Check that the fonts, margins and line spacing are conforming the the 4th yr project guidelines. The fonts look a little small to me, but it might be my eyes that are getting older."
He's right about this:
  - We need to bump it from font 11 to 12. 
  - It should also be double spaced.
------------
- [x] **(Justin)** 8.2.2 typo in the last line: "making THE analyzer"
------------
- [x] **(Justin)** 8.1.2 provide a bit of text describing the diagrams you have.
------------
- [x] **(Justin)** 8.3 is excellent. I have nothing to add!
------------
- [x] **(Ismail)** 8.4 I was surprised to find GraphiQL stuff *after* webscale. Ideally, the webscale chapter should show how the developer of webscale uses GraphiQL to discover the n+1 queries etc. Also, this is a chapter that talks about React components, and since webscale also uses React, it makes sense for webscale to leverage this description to also explain what React components were written for webscale.
------------
- [x] **(Ismail)** 8.4.1 typo parag 1: "its" vs "it's"
------------
- [x] **(Derek, figure police)** broken figure ref p53
------------
- [x] **(Justin)** 9: "sheer vs shear"
------------
- [x] chapter 9 is a bit short... expand on what you did and what's left to be done.
------------
- [x] didn't see much talk about testing, yet I do know you wrote tests (you also mentioned RSpec in the report)... talk about what was unit-tested, what integration tests you wrote, did you test the React stuff and how (Jasmine? Moka?).
------------
- [x] maybe also talk about the performance overhead of using the analyzer vs not using it.

**Comment by DerekStride** [comment]
> chapter 9 is a bit short... expand on what you did and what's left to be done

Can we add parts to the conclusion about the demo application and the plugins?

> Chap 8 might need an intro. In general, start each chapter with a little intro so we know ...

Added this to chapter 8 and 8.2

**Comment by DerekStride** [comment]
>didn't see much talk about testing, yet I do know you wrote tests (you also mentioned RSpec in the report)... talk about what was unit-tested, what integration tests you wrote, did you test the React stuff and how (Jasmine? Moka?). 

Added a testing section for the analyzer

**Comment by ismail-syed** [comment]
>  (Ismail) 7.7, 7.8 up to 7.11 might need to be under the same umbrella, maybe something called "Background".

This has been refactored to all exist under section "7.7 Interoperability Background"

**Comment by ismail-syed** [comment]
> talk about what was unit-tested, what integration tests you wrote, did you test the React stuff and how (Jasmine? Moka?).

I added a section on tests for the graphiql plugins under section _8.3.4 Testing_
