### ISSUE TITLE
Weekly Health Checks

### ISSUE THREAD

**Issue by DerekStride** [GraphQL-Query-Planner/project#5]
This comment thread will be used for weekly health checks.

@justinkrol @ismail-syed @DerekStride

**Comment by ismail-syed** [comment]
## Health Check 1: Sept 14th


As per our first meeting today with Babak, below are the tasks we plan to tackle this week. Since our proposal is due Tues, Sept. 19, our tasks gravitate more towards proposal based tasks. 

### Justin: 
* Add some Diagrams for the proposal  (Use case diagram)
* Add section on describing our project management tools (GitHub, Issues, Milestones, Google Drive)

###  Ismail: 
* More detailed overview of the web application and expand on the milestones.
* How it will demonstrate findings and metrics from the query planner in a visually meaningful manner.

### Derek
* Rewrite the GraphQL and Query planner background section
* Expand on milestones for Query planner

--- 
We have also added these tasks into our Github repository: 
https://github.com/GraphQL-Query-Planner/project/issues

**Comment by DerekStride** [comment]
## Health Check 2: Sept 21st

### Justin: 
* Setup Migrations
- Review Report and ensure consistent with style guidlines (@justinkrol)

###  Ismail: 
* Setup MySQL with Rails
* Local machine setup added to README
- What is GraphQL? (@ismail-syed)
	- Controller Structure (query)
	- mutation, query, subscription
	- Type system and Schema
	- Query Syntax, and response syntax

### Derek
* Setup GraphQL Types and Schema
- What is REST? (@derekstride)
	- Resources
	- CRUD 
	- Controller Structure (index, show, new, edit, create, update, delete)

### All
- Pair on Sunday to investigate query planning

**Comment by justinkrol** [comment]
## Health Check 3: Sept 28th

### Justin:
- Continue reviewing/updating report structure
- Add section to report about the model that was added to the web-app
- Get through reading list

### Ismail:
- continue with REST section of report
- continue GraphQL section of report
- Get through reading list

### Derek:
- Update proposal/report about forking Graphiql to include the planner (dropdown), or having the gem separately extend the Graphiql view.
- Finish up GraphQL part of web-app
  - add info to report describing these changes
- Get through reading list

### Later
- Wireframe designs for report to better understand goals for what we want to build.
- Deployment diagrams, model diagrams, pseudocode, explain the code/structure/architecture in some way.
- Explain any important algorithms that we implement.
- Investigate a SQL query parser
- Look into distributing as two gems:
  - Query planner/optimizer gem
  - Query analyzer gem (addition to Graphiql)

**Comment by DerekStride** [comment]
## Health Check 4: Oct 5th

### Justin:
- Finish seeding library to setup our database with sample data
- Update milestones with our plans to extract webscale into a gem
- add REST API for our data models

### Ismail:
- Finish GraphQL fields for relationships between our data models
- add REST API for our data models

### Derek:
- Setup Indexes for our data models
- Add section to the report about what a a backend and a resolver is

**Comment by ismail-syed** [comment]
## Health Check 5: Oct 12th

### Ismail: 
- [x] Set up continuous integration with Travis CI
- [x] Finish GraphQL field resolves for relation models on Likes and Comments

### Justin: 
- [ ] Finish REST endpoints for Likes and Comments model 
- [ ] Add tests for GraphQL 

### Derek: 
- [ ] Explain GraphQL in more detail with regards to what was discussed in our meeting (tree structure)
- [ ] Add tests for REST 

### Other tasks gathered from our meeting if the ones above are completed by next week

- [ ] Add wireframes to document with screenshots of REST and GraphQL responses
- [ ] Add a section talking about the GraphQL Gem, what it provides, how to use it
- [ ] Add a section on GraphiQL, the GraphiQL Gem, what it provides, how to use it
- [ ] Add a section on Rails & ActiveRecrods, what it provides, how to use it

**Comment by ismail-syed** [comment]
## Follow-up: Health Check 5: Oct 17th

### Ismail: 
- (Done) Added Travis-CI to repository
- (In progress) Adding a continuous integration section in Report
- (In progress) Added test for REST API endpoints for User and models

### Derek: 
I was quite busy this week and didn't get as much done. I'll be pushing some of this stuff into next week.
- (Pending) Explain GraphQL in more detail with regards to what was discussed in our meeting (tree structure)
- (In progress) Add tests for REST

### Justin
I was also pretty busy, so I only added a change to fix the way we seed posts, photos, comments, and likes.
- (Pending) Finish REST endpoints for Likes and Comments model
- (Pending) Add tests for GraphQL

**Comment by DerekStride** [comment]
## Health Check 6: Oct 19th

### Ismail: 
- [x] Finish GraphQL field resolves for relation models on Likes and Comments

### Justin: 
- [x] Finish REST endpoints for Likes and Comments model
- [ ] Add tests for GraphQL

### Derek: 
- [x] Explain GraphQL in more detail with regards to what was discussed in our meeting (tree structure)
- [ ] Update Objectives section

**Comment by ismail-syed** [comment]
## Health Check 7: Nov 2nd

### Ismail: 
- [x] Add a section talking about the GraphQL Gem, what it provides, how to use it (1 week)
  - [ ] Illustrate exact what happens, the issue, and the solution. (1 week)
  - [ ] How does our tool help, what are the issues without the tool (1 week)
- [x] Add a section on GraphiQL, the GraphiQL Gem, what it provides, how to use it (1 week)
- [x] Set up tooling to do development on a GraphiQL fork in webscale (2 weeks)

### Justin: 
- [ ] GraphQL tests that ensure unoptimized queries (2 week)
- [ ] Look into UI, visualization (3 weeks)

Report updates: 
- [ ] Deep dive to unify explanations, unify report style (2 weeks) 
- [x] Add page numbers and automated table numbering to the report (1 week)
- [ ] Update the use case diagrams more, discuss in more detail (1 week)
- [ ] Remove the old webscale sections and talk about the new plans in more detail. (2 weeks)
  - [ ] How does it interact with the query planner. 
  - [ ] What is the current development workflow like with graphql-ruby and graphiql vs our forks of them

### Derek: 
- [x] Continue building the actual analyzer portion of the project (2 weeks)
- [x] Explore more in dept of what the potential API of the planner will be (2 weeks)
- [x] Add all these technical findings to the report (2 weeks)
- [x] Draw a sequence diagram of the execution of a GraphQL Query.

**Comment by ismail-syed** [comment]
## Health Check - Follow up: Nov 15th: 

### Ismail
- [Report] Added a section on graphql-ruby
- [Report] Added a section on Webscale (this will grow as we do more development)

### Derek
- Added Query Execution sequence diagram.
- Minor schema tweaks
- Analyzer MVP finalized

### Justin
- graphql tests ensuring problems
- updated use case diagram

**Comment by ismail-syed** [comment]
## Health Check: Nov 16th: 

### Ismail
* [Report] Talk about GraphiQL dev tech stack : JS & React background
* [Report] Move webscale much higher in the report and talk more about it's purpose
  * It's a server with data hosted on MySQL (talk about MySQL)
* [Experiment] Run larger data sets to decide on what visualizations would be most appropriate for the report analysis pane
* [Development] Start JavaScript/React development on GraphiQL to create tabbable pane 


### Derek
- [x] [Development] Start extracting code into a gem so we can test on other applications (1 week)
- [ ] [Development] Add ElasticSearch query detection and refactor to support multiple datastores (2 weeks)
- [ ] [Report] Create another diagram to show how we redefine fields to add our instrumentation (2 weeks)
- [ ] [Report] Add a section on ElasticSearch (2-3 weeks)

### Justin
- [x] [Report] Add use case descriptions (1 week)
- [ ] [Development] Work with Ismail on front-end (2 weeks)
- [ ] [Report] Higher fidelity mock ups of user interface (1 week)

**Comment by DerekStride** [comment]
## Health Check: Follow-up Nov 23th: 

### Derek
- (done) [Development] Start extracting code into a gem so we can test on other applications (1 week)
- (up next) [Development] Add ElasticSearch query detection and refactor to support multiple datastores (2 weeks)
- (pending) [Report] Create another diagram to show how we redefine fields to add our instrumentation (2 weeks)
- (pending) [Report] Add a section on ElasticSearch (2-3 weeks)

### Ismail
* (DONE) [Report] Talk about GraphiQL dev tech stack :  Added React, JavaScript, DOM sections to the report background
* (DONE) [Report] Move webscale much higher in the report
  * (pending) Expand on webscale description more
  * (pending) It's a server with data hosted on MySQL (talk about MySQL)
*  (pending) [Experiment] Run larger data sets to decide on what visualizations would be most appropriate for the report analysis pane
* (pending) [Development] Start JavaScript/React development on GraphiQL to create tabbable pane 

### Justin
* (DONE) [Report] Add Use Case descriptions
* (DONE) [Development] Basic tests ensuring N+1 and missing index
* (In progress) [Report] Higher fidelity mockups (based on use cases)
* (Up next) [Development] Start working on UI changes

**Comment by ismail-syed** [comment]
## Health Check:  Jan 16th: 

### Derek
- Add Travis CI integration to graphql-analyzer
- Complete ActiveRecord testing refactor for graphql-analyzer so we can run a test suite on each Datastore we support.

### Ismail
* Added tabbable plugins pane for the GraphiQL editor
* Added sections in the report regarding the React implementation with code snippets (Page 33 in blue)
* TODO: Add a UML for the plugins pane layouts

### Justin
* Update the GraphiQL plugins pane to be resizeable
* Looking into how to build a "plugin" that will display the "extensions" part of the data that gets returned
