### ISSUE TITLE
Create use case diagrams for the planner

### ISSUE THREAD

**Issue by DerekStride** [GraphQL-Query-Planner/project#6]

**Comment by justinkrol** [comment]
I've added a single UCD to the [proposal](https://docs.google.com/document/d/1fun70FFe5heoWo8c3EdgCStcaAxJa-5wjn2Mg0Ahwhc/edit).  There's basically one main use case, `Plan Query`, which includes `Plan Query for Individual Backend`. That includes `Check Queries` and `Identify Indexes`.
The two actors are `Developer`, and `Backend`.

cc @DerekStride @ismail-syed
